name: deploy

on:
  push:
    branches: # master に直接pushしたとき
      - master
  pull_request: # PullRequest作成、同期時に実行させる
    types:
      - opened
      - synchronize
    branches:
      - "**"  # 全てのブランチを対象とする
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          make pip_dev
      - name: Run Tests
        run: |
          make lint
          make test
