name: deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
jobs:
  lambda-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - run: |-
          cd functions
          zip -r ../package.zip *
          cd ..
      - run: pip3 install awscli
      - run: aws lambda update-function-code --function-name maidchanbot --zip-file fileb://package.zip --publish
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
      - run: |-
          curl -X POST --data-urlencode \
          "payload={\"channel\": \"#雑談カフェ\", \"username\": \"メイドちゃん\", \"text\": \"メイドちゃんのレベルが上がったよ！(^o^)\", \"icon_emoji\": \":maidchan:\"}"\
          https://hooks.slack.com/services/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
